name: myenv
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - jupyter
  - ipython
  - ipykernel
  - pip:
    - scanpy
    - matplotlib
    - pandas
    - numpy
    - seaborn
    - statsmodels
